### ISSUE TITLE
Model.IDC and Model.PIN Not found in references

### ISSUE THREAD

**Issue by chienits** [mortezabarzkar/XFS4NET#1]
Hello, can you help me resloved error in project XFS4NET

In MainWindow.xaml.cs was missing using references
using XFS4NET.Model.IDC;
using XFS4NET.Model.PIN;

**Comment by mortezabarzkar** [comment]
project was archived .

**Comment by kazepis** [comment]
@mortezabarzkar could you provide the missing references?

**Comment by mortezabarzkar** [comment]
@chienits 
@kazepis 
I will resolve missing references this week

**Comment by kazepis** [comment]
@mortezabarzkar thank you very much for your time and effort!
